const motsParDefaut = [
  "Napoléon",
  "Albert Einstein",
  "Beyoncé",
  "Marilyn Monroe",
  "Michael Jackson",
  "Léonard de Vinci",
  "Elon Musk",
  "Simone Veil",
  "Cléopâtre",
  "Mahatma Gandhi",
  "Martin Luther King",
  "Marie Curie",
  "Steve Jobs",
  "Victor Hugo",
  "Nelson Mandela",
  "Pablo Picasso",
  "Barack Obama",
  "Isaac Newton",
  "Julius César",
  "Frida Kahlo",
  "Harry Potter",
  "Mickey Mouse",
  "Sherlock Holmes",
  "Cendrillon",
  "Tarzan",
  "Batman",
  "Wonder Woman",
  "Simba",
  "James Bond",
  "Luke Skywalker",
  "Darth Vader",
  "Homer Simpson",
  "Spider-Man",
  "Elsa",
  "Shrek",
  "Hercule",
  "Alice au pays des merveilles",
  "Peter Pan",
  "Aladdin",
  "Gandalf",
  "Tour Eiffel",
  "Machu Picchu",
  "Muraille de Chine",
  "Pôle Nord",
  "Sahara",
  "Amazonie",
  "Mont Everest",
  "Pyramides d'Égypte",
  "Grand Canyon",
  "Statue de la Liberté",
  "Taj Mahal",
  "Mont Fuji",
  "Big Ben",
  "Venise",
  "Cap Canaveral",
  "Château de Versailles",
  "Colisée",
  "Stonehenge",
  "Chutes du Niagara",
  "Vatican",
  "Chat",
  "Chien",
  "Dauphin",
  "Tigre",
  "Perroquet",
  "Panda",
  "Éléphant",
  "Loup",
  "Tortue",
  "Kangourou",
  "Zèbre",
  "Cheval",
  "Pingouin",
  "Hérisson",
  "Lion",
  "Girafe",
  "Requin",
  "Coccinelle",
  "Ours polaire",
  "Singe",
  "Téléphone",
  "Bouteille",
  "Stylo",
  "Montre",
  "Ordinateur",
  "Lunettes",
  "Livre",
  "Chaise",
  "Sac à dos",
  "Vélo",
  "Table",
  "Lampe",
  "Couteau",
  "Valise",
  "Radio",
  "Télévision",
  "Clé",
  "Chaussures",
  "Brosse à dents",
  "Voiture",
  "Pizza",
  "Chocolat",
  "Croissant",
  "Sushi",
  "Banane",
  "Fromage",
  "Café",
  "Spaghetti",
  "Glace",
  "Jus d'orange",
  "Pain",
  "Poulet",
  "Tarte",
  "Hamburger",
  "Frites",
  "Riz",
  "Miel",
  "Carotte",
  "Pomme",
  "Céréales",
  "Médecin",
  "Pompier",
  "Infirmière",
  "Avocat",
  "Pilote",
  "Architecte",
  "Enseignant",
  "Cuisinier",
  "Vétérinaire",
  "Astronaute",
  "Policier",
  "Musicien",
  "Acteur",
  "Scientifique",
  "Dentiste",
  "Plombier",
  "Chauffeur",
  "Journaliste",
  "Photographe",
  "Boulanger",
  "Football",
  "Tennis",
  "Yoga",
  "Natation",
  "Escalade",
  "Cyclisme",
  "Ski",
  "Peinture",
  "Danse",
  "Jardinage",
  "Basketball",
  "Course à pied",
  "Aviron",
  "Boxe",
  "Équitation",
  "Golf",
  "Surf",
  "Pêche",
  "Volleyball",
  "Escrime",

  "Mariage",
  "Anniversaire",
  "Vacances",
  "Carnaval",
  "Révolution",
  "Concert",
  "Pluie",
  "Amour",
  "Amitié",
  "Travail",
  "Paix",
  "Fête",
  "Guerre",
  "Noël",
  "Halloween",
  "Pâques",
  "Nouvel An",
  "École",
  "Hôpital",
  "Rêve",
  "Fantôme",
  "Robot",
  "Arc-en-ciel",
  "Montagne",
  "Pirate",
  "Magicien",
  "Sirène",
  "Étoile",
  "Forêt",
  "Trésor",
  "Dragon",
  "Fée",
  "Feu",
  "Glace",
  "Orage",
  "Océan",
  "Lune",
  "Soleil",
  "Nuage",
  "Éclair",
  "Désert",
  "Lac",
  "Plage",
  "Cheminée",
  "Jardin",
];

export default motsParDefaut;
